umass_ghpcc_lsf:
    cluster_type: lsf
    job_time: 04:00
    project: /project/umw_athma_pai
    queue: short
    workers_per_job: 10
    num_workers: 10
    min_num_workers:
    worker_cores: 1
    worker_memory: 2048
    debug: True
