umass_ghpcc_lsf_short:
    cluster_type: lsf
    job_time: 04:00
    project: /project/umw_athma_pai
    queue: short
    workers_per_job: 2
    num_workers: 100
    min_num_workers:
    worker_cores: 5
    worker_memory: 4096
    debug: True
umass_ghpcc_lsf_long:
    cluster_type: lsf
    job_time: 04:00
    project: /project/umw_athma_pai
    queue: long
    workers_per_job: 2
    num_workers: 20
    min_num_workers:
    worker_cores: 2
    worker_memory: 4096
    debug: True
umass_ghpcc_lsf_basecall:
    cluster_type: lsf
    job_time: 04:00
    project: /project/umw_athma_pai
    queue: short
    workers_per_job: 2
    num_workers: 100
    min_num_workers:
    worker_cores: 4
    worker_memory: 16284
    debug: True
umass_c3ddb_slurm:
    cluster_type: slurm
    job_time: 04:00
    project:
    queue: defq
    workers_per_job: 4
    num_workers: 12
    min_num_workers:
    worker_cores: 2
    worker_memory: 4096
    debug: True
local:
    cluster_type: local
