#!/bin/bash

MEM=10240
THREADS=5
CORES=5

#BSUB -J albacore_test1
#BSUB -q short
#BSUB -P /project/umw_athma_pai
#BSUB -n $CORES
#BSUB -R "span[hosts=1]"
#BSUB -M 10240
#BSUB -W 03:00
#BSUB -R "rusage[mem=$MEM]"


read_fast5_basecaller.py --flowcell FLO-MIN106 --kit SQK-LSK109 --output_format fastq --save_path /project/umw_athma_pai/kevin/data/Albacore_tests/without_nanopypes --worker_threads $THREADS --input /project/umw_athma_pai/kevin/data/minion_ercc_labeled/20190220_1525_ERCC/fast5/pass/albacore_test --reads_per_fastq_batch 1000


