pipeline_id: albacore_ercc
pipeline_tools: [["albacore", "basecall"]]
pipeline_order:
    matrix_0:
        input_data:
            path: ""
            type: "ont_directories_single_read_fast5"
        partition_transform:
            batch_size: 2
            partitions: 5
        data_transform_order: [["albacore", "basecall"]]
        merge_transforms: {}

pipe_configs:
    albacore:
        task_kwargs: {}
        task_type: shell
        image_path: ""
        commands:
            basecall:
                template: "read_fast5_basecaller.py --input {input} --save_path {save} --flowcell {flowcell} --kit {kit} --output_format fastq --worker_threads 1 --reads_per_fastq 1000" #"echo {input} {save} {flowcell} {kit}"
                user_input: ['reference']
                save_path: "/Users/kevinfortier/Desktop/NanoPypes_Prod/NanoPypes/tests/test_data/basecalled_data/results/local_basecall_test"
