pipeline_id: demulti_mapper
pipeline_tools: [["albacore", "basecall"], ["minimap2", "splice-map"], ["samtools", "sam_to_bam"], ["samtools", "merge_bams"]]
pipeline_order:
    matrix_0:
        input_data:
            path: ""
            type: "ont_directories_single_read_fast5"
        partition_transform:
            batch_size: 2
            partitions: 5
        data_transform_order: [["albacore", "basecall"], ["minimap2", "splice-map"], ["samtools", "sam_to_bam"]]
        merge_transforms:
            2: ["samtools", "merge_bams"]
#    matrix_1:
#        input_data:
#            matrix_transform: ["matrix_0", ["albacore", "basecall"]]
#        data_transform_order: [["albacore", "basecall"], ["nanoplot", "nanoplot"]]
#        merge_transforms:
#            0: []
pipe_configs:
    albacore:
        task_kwargs: {}
        task_type: shell
        image_path: ""
        commands:
            basecall:
                template: "read_fast5_basecaller.py --input {input} --save_path {save} --flowcell {flowcell} --kit {kit} --output_format fastq --worker_threads 1 --reads_per_fastq 1000" #"echo {input} {save} {flowcell} {kit}"
                user_input: ['reference']
                save_path: "/Users/kevinfortier/Desktop/NanoPypes_Prod/NanoPypes/tests/test_data/basecalled_data/results/local_basecall_test"
    minimap2:
        task_kwargs: {}
        task_type: shell
        image_path: ""
        commands:
            splice-map:
                template:  "minimap2 -ax splice {reference} {input} > {save}" #"echo minimap2 -ax splice {reference} {input} {save}"
                user_input: ['reference']
                save_path: "/Users/kevinfortier/Desktop/NanoPypes_Prod/NanoPypes/tests/test_data/mapped_reads"
    porechop:
        task_kwargs: {}
        task_type: shell
        image_path: ""
        commands:
            demultiplex:
                template: "porechop -i {input} -b {save}"
                user_input: []
                save_path: "/Users/kevinfortier/Desktop/NanoPypes_Prod/NanoPypes/tests/test_data/demultiplexed_data"
